---
baseurl: '/typing'
url: 'http://localhost:8899'

maintenance:
    enable: false
google:
    analytics:
        enable: true
home:
    # NEW!
    terminal:
        enable: false

sidebar:
    avatar:
        enable: true
    # NEW!
        flip: false
    icons:
        enable: true
    socials:
        enable: true
content:
    icons:
        enable: true
    postlist:
        date:
            enable: true
        expected:
            enable: true
        tags:
            enable: true
        comments:
            enable: true
    tagpost:
        date:
            enable: true
        expected:
            enable: true
        tags:
            enable: true
        comments:
            enable: true
    post:
        author:
            enable: true
            avatar:
                enable: false
        share:
            enable: true
            facebook:
                enable: true
            linkedin:
                enable: true
            twitter:
                enable: true
        day_quote:
            enable: true
        comments:
            enable: true
    contact:
        note:
            enable: true


jektify:
    enable: true
    open: true
    toggle:
        enable: true
    spotify:
        user: "you_user"
        text: "See me no Spotify"
    sass:
        jekyll: true
        other:
            dir: "way/to/your/SASS"
    title:
        enable: false
        text: "Música"
    description:
        enable: false
        text: "Jekyll plugin"


plugins:
     - jektify
    - jemoji
    - jekyll-paginate-v2

    # Settings for the plugins in the _plugins folder.
_plugins:
    imager:
        dir_posts: "assets/images/posts"
    # To see language support, go to the plugin "_plugins/reading_time.rb"
    reading_time:
        locale: en_US
    # To see language support, go to the plugin "_plugins/datelang.rb"
    datelang:
        locale: en_US
        reload: false

# Settings Default
include: ['_blog', '_pages', '_contact']
markdown: kramdown
highlighter: pygments
permalink: /blog/:title/

# Build local / Server
destination: _site
port: 4000
host: localhost

# Config SASS
sass:
    sass_dir: _sass
    style: compressed

# Config feed for atom
feed:
    path: atom.xml

# Config for Compress HTML
compress_html:
    clippings: all
    comments: all
    endings: []
    profile: false

# Config plugin 'jekyll-tagging'
tag_page_layout: tag
tag_page_dir: blog/tags
tag_permalink_style: pretty


pagination:
    enabled: true
    debug: false
    collection: 'posts'
    sort_field: 'date'
    sort_reverse: true
    per_page: 5
    permalink: '/blog/:num/'
    locale: ''
    title: ':title - Page :num'
    limit: 0
    extension: html
    indexpage: 'index'

# Config for plugin 'jekyll-gist'
gist:
    noscript: false

# Exclude files (or folders) in compilation.
exclude:
    - docs
    - development
    - src
    - vendor
    - Gemfile
    - Gemfile.lock
    - screenshot.png
    - CHANGELOG
    - LICENSE.txt
    - COPYING
    - "**/*.txt"
    - README.md
    - init.sh
    - Rakefile
    - deploy.conf
